meta_product_name: "PimpYourPrint"
meta_title: "Challenge your habits to reduce your footprint | PimpYourPrint"
meta_description: "Fulfill simple daily challenges to reduce efficiently your carbon footprint. Keep track of your progress and make a difference!"
meta_image: "mirrored-forest-facebook.jpg"
